ok

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,53 @@
+
+
+# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
 language: c
+env:
+  # Build and test against the master and devel branches of Nim
+  - BRANCH=master
+  #- BRANCH=devel
 compiler:
+  # Build and test using both gcc and clang
   - gcc
-before_install:
-  # Install nim
-  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
-  - cd Nim
-  - git clone -b devel --depth 1 git://github.com/nim-lang/csources
-  - cd csources && sh build.sh
-  - cd ..
-  - bin/nim c koch
-  - ./koch boot -d:release
-  - export PATH=$PWD/bin:$PATH
-  - cd ..
-    
+  - clang
+matrix:
+  allow_failures:
+    # Ignore failures when building against the devel Nim branch
+    - env: BRANCH=devel
+  fast_finish: true
+install:
+  - |
+    if [ ! -x nim-$BRANCH/bin/nim ]; then
+      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
+      cd nim-$BRANCH
+      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/csources csources/
+      cd csources
+      sh build.sh
+      cd ..
+      rm -rf csources
+      bin/nim c koch
+      ./koch boot -d:release
+    else
+      cd nim-$BRANCH
+      git fetch origin
+      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
+        bin/nim c koch
+        ./koch boot -d:release
+      fi
+    fi
+    cd ..
+before_script:
+    - export PATH="nim-$BRANCH/bin${PATH:+:$PATH}"
 script:
-  - nim c --run nfT52
-  
-  
-  
+    # Replace uppercase strings!
+    - nim c --cc:$CC --verbosity:0 -r nfT52.nim
+    # Optional: build docs.
+    #- nim doc --docSeeSrcUrl:https://github.com/AUTHOR/MYPROJECT/blob/master --project MYFILE.nim
+cache:
+  directories:
+    - nim-master
+    - nim-devel
+branches:
+  except:
+    - gh-pages
+
